# Generated by Django 5.1.3 on 2024-11-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.AddField(
            model_name='pledge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pledge_images/'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
