# Generated by Django 5.1.3 on 2024-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_achievement_user_delete_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='author',
            field=models.CharField(default='author', max_length=225),
        ),
    ]
