# Generated by Django 5.1.3 on 2024-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_pledge_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
